### ISSUE TITLE
关于 Abuse（滥用）

### ISSUE THREAD

**Issue by arischow** [rptec/squid-PAC#7]
想请问作者在共享免费代理时，除了在防火墙上屏蔽端口，还有没有其他办法避免使用者利用其发送垃圾邮件等滥用行为而导致被空间商投诉的？

谢谢。

**Comment by rptec** [comment]
@arischow 邮件也可以通过  squid代理吗？
 squid  我的conf文件里，只是开放了 http和ftp等，，，而POP3/IMAP/SMTP  这些端口，，并未开放，，不能通过代理的。。。
所以 这个代理仅限 http/ftp，再加上  killall sendmail，，25端口也无法发送邮件。  所以一般来说 你不需要担心，因为垃圾邮件而被投诉。。
